name: Build LaTeX document
on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true

      - name: Upload generated PDF
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
      - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.3
          with:
            branch: gh-pages # Change this to the desired branch
            folder: . # Change this to the folder containing the PDF
            clean: true
            token: ${{ secrets.GITHUB_TOKEN }}
