name: Build LaTeX document
on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true

      - name: Upload generated PDF
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
      - name: Upload S3    
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: jerikjakobsen-resume-bucket
          source_dir: 'resume.pdf'
      - name: Link To Report
        run: echo "https://s3.amazonaws.com/jerikjakobsen-resume-bucket/resume.pdf"
