name: Build LaTeX document
on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        latexmk-args: "-pdf -
